
DRIVE_LOOP_HZ = 35      # the vehicle loop will pause if faster than this speed.

OBSTACLE_DETECTOR_MODEL_PATH = "/home/donkey/donkeycar-models/trt_4.6/model-A022.trt"

# # Following values must be aligned with values in Hat !
# ROBOCARSHAT_PWM_OUT_THROTTLE_MIN    =   1000
# ROBOCARSHAT_PWM_OUT_THROTTLE_IDLE   =   1500
# ROBOCARSHAT_PWM_OUT_THROTTLE_MAX    =   2000
ROBOCARSHAT_PWM_OUT_STEERING_MIN    =   1180
ROBOCARSHAT_PWM_OUT_STEERING_IDLE   =   1520
ROBOCARSHAT_PWM_OUT_STEERING_MAX    =   1940
# ROBOCARSHAT_PWM_OUT_STEERING_INVERT    =   False

# # Folowing values can be ajusted to normalized btzeen -1 and 1.
# # # If  ROBOCARSHAT_USE_AUTOCALIBRATION is used, IDLE values are automatically identified by the Hat
ROBOCARSHAT_PWM_IN_THROTTLE_MIN    =   1004
# ROBOCARSHAT_PWM_IN_THROTTLE_IDLE   =   1500
ROBOCARSHAT_PWM_IN_THROTTLE_MAX    =   1982
ROBOCARSHAT_PWM_IN_STEERING_MIN    =   995
# ROBOCARSHAT_PWM_IN_STEERING_IDLE   =   1500
ROBOCARSHAT_PWM_IN_STEERING_MAX    =   1985
# ROBOCARSHAT_PWM_IN_AUX_MIN    =   1000
# ROBOCARSHAT_PWM_IN_AUX_IDLE   =   1500
# ROBOCARSHAT_PWM_IN_AUX_MAX    =   2000

ROBOCARSHAT_CONTROL_LED = True
ROBOCARSHAT_CONTROL_LED_DEDICATED_TTY = '/dev/ttyACM0'

# PROFILES
ROBOCARS_CONFIG_PROFILE_IARACING_SPRINT_FIXSPEED = {
    'ROBOCARS_PROFILE_NAME' : 'IARACING-SPRINT',
    'ROBOCARSHAT_PILOT_MODE' : 'local_angle',
    'ROBOCARS_THROTTLE_DUAL_THROTTLE_MODEL' : 'False',
    'ROBOCARSHAT_LOCAL_ANGLE_FIX_THROTTLE' : 0.17,
    'ROBOCARS_CTRL_ADAPTATIVE_STEERING_SCALER': 0.3,
    'OBSTACLE_DETECTOR_AVOIDANCE_ENABLED' : False,
    'OBSTACLE_DETECTOR_MANUAL_LANE' : True,
    'ROBOCARSHAT_THROTTLE_FLANGER' : [-0.2, 0.25]
}

# 2
ROBOCARS_CONFIG_PROFILE_IARACING_SPRINT = {
    'ROBOCARS_PROFILE_NAME' : 'IARACING-SPRINT',
    'ROBOCARSHAT_PILOT_MODE' : 'local',
    'ROBOCARS_THROTTLE_DUAL_THROTTLE_MODEL' : 'True',
    'ROBOCARS_THROTTLE_LOW' : 0.19,
    'ROBOCARS_THROTTLE_HIGH' : 0.23,
    'ROBOCARSHAT_LOCAL_ANGLE_FIX_THROTTLE' : 0.17,
    'ROBOCARS_CTRL_ADAPTATIVE_STEERING_SCALER': 0.0,
    'OBSTACLE_DETECTOR_AVOIDANCE_ENABLED' : False,
    'OBSTACLE_DETECTOR_MANUAL_LANE' : True,
    'ROBOCARSHAT_THROTTLE_FLANGER' : [-0.2, 0.25]
}

# 3
ROBOCARS_CONFIG_PROFILE_IARACING_SLALOM = {
    'ROBOCARS_PROFILE_NAME' : 'IARACING-SLALOM',
    'ROBOCARSHAT_PILOT_MODE' : 'local',
    'ROBOCARS_THROTTLE_DUAL_THROTTLE_MODEL' : 'False',
    'ROBOCARS_THROTTLE_LOW' : 0.17,
    'ROBOCARS_THROTTLE_HIGH' : 0.17,
    'ROBOCARSHAT_LOCAL_ANGLE_FIX_THROTTLE' : 0.17,
    'ROBOCARS_CTRL_ADAPTATIVE_STEERING_SCALER': 0.0,
   'OBSTACLE_DETECTOR_AVOIDANCE_ENABLED' : True,
    'OBSTACLE_DETECTOR_MANUAL_LANE' : False,
    'ROBOCARSHAT_THROTTLE_FLANGER' : [-0.2, 0.25]
}

# 1 & 4
ROBOCARS_CONFIG_PROFILE_COPILOT_SPRINT_FLANGER_LOW = {
    'ROBOCARS_PROFILE_NAME' : 'IARACING-SPRINT-FLANGER-LOW',
    'ROBOCARSHAT_PILOT_MODE' : 'local_angle',
    'ROBOCARS_THROTTLE_DUAL_THROTTLE_MODEL' : 'False',
    'ROBOCARS_CTRL_ADAPTATIVE_STEERING_SCALER': 0.0,
    'ROBOCARSHAT_LOCAL_ANGLE_FIX_THROTTLE' : None,
    'OBSTACLE_DETECTOR_AVOIDANCE_ENABLED' : False,
    'OBSTACLE_DETECTOR_MANUAL_LANE' : True,
    'ROBOCARSHAT_THROTTLE_FLANGER' : [-0.2, 0.25]
}

ROBOCARS_CONFIG_PROFILE_COPILOT_SPRINT_FLANGER_HIGH = {
    'ROBOCARS_PROFILE_NAME' : 'IARACING-SPRINT-FLANGER-HIGH',
    'ROBOCARSHAT_PILOT_MODE' : 'local_angle',
    'ROBOCARS_THROTTLE_DUAL_THROTTLE_MODEL' : 'False',
    'ROBOCARS_CTRL_ADAPTATIVE_STEERING_SCALER': 0.0,
    'ROBOCARSHAT_LOCAL_ANGLE_FIX_THROTTLE' : None,
    'OBSTACLE_DETECTOR_AVOIDANCE_ENABLED' : False,
    'OBSTACLE_DETECTOR_MANUAL_LANE' : True,
    'ROBOCARSHAT_THROTTLE_FLANGER' : [-0.3, 0.3]
}

ROBOCARS_CONFIG_PROFILE_COPILOT_SPRINT_NO_FLANGER = {
    'ROBOCARS_PROFILE_NAME' : 'IARACING-SPRINT-NO-FLANGER',
    'ROBOCARSHAT_PILOT_MODE' : 'local_angle',
    'ROBOCARS_THROTTLE_DUAL_THROTTLE_MODEL' : 'False',
    'ROBOCARS_CTRL_ADAPTATIVE_STEERING_SCALER': 0.0,
    'ROBOCARSHAT_LOCAL_ANGLE_FIX_THROTTLE' : None,
    'OBSTACLE_DETECTOR_AVOIDANCE_ENABLED' : False,
    'OBSTACLE_DETECTOR_MANUAL_LANE' : True,
    'ROBOCARSHAT_THROTTLE_FLANGER' : None,
    'ROBOCARSHAT_THROTTLE_FLANGER' : [-0.2, 0.25]
}

ROBOCARS_CONFIG_PROFILE_COPILOT_SLALOM = {
    'ROBOCARS_PROFILE_NAME' : 'IARACING-SLALOM',
    'ROBOCARSHAT_PILOT_MODE' : 'local_angle',
    'ROBOCARS_CTRL_ADAPTATIVE_STEERING_SCALER': 0.0,
    'ROBOCARSHAT_LOCAL_ANGLE_FIX_THROTTLE' : None,
    'OBSTACLE_DETECTOR_AVOIDANCE_ENABLED' : True,
    'OBSTACLE_DETECTOR_MANUAL_LANE' : False,
    'ROBOCARSHAT_THROTTLE_FLANGER' : [-0.2, 0.25]
}

# 1 SPRINT COPILOT
# python manage.py drive --type trt_behaviortrt --model ~/donkeycar-models/trt_4.6/model-067.trt
#ROBOCARS_CONFIG_PROFILE = ROBOCARS_CONFIG_PROFILE_COPILOT_SPRINT_FLANGER_LOW

# 2 SPRINT AI
# python manage.py drive --type trt_behaviortrt --model ~/donkeycar-models/trt_4.6/model-067.trt
#ROBOCARS_CONFIG_PROFILE = ROBOCARS_CONFIG_PROFILE_IARACING_SPRINT

# 3 SLALOM AI
# python manage.py drive --type trt_behaviortrt --model ~/donkeycar-models/trt_4.6/model-067.trt
#ROBOCARS_CONFIG_PROFILE = ROBOCARS_CONFIG_PROFILE_IARACING_SLALOM
#ROBOCARS_CONFIG_PROFILE = ROBOCARS_CONFIG_PROFILE_COPILOT_SLALOM

# 4 PARADE
# python manage.py drive --type trt_behaviortrt --model ~/donkeycar-models/trt_4.6/model-067.trt
ROBOCARS_CONFIG_PROFILE = ROBOCARS_CONFIG_PROFILE_COPILOT_SPRINT_FLANGER_LOW
