DRIVE_LOOP_HZ = 35

OBSTACLE_DETECTOR_MODEL_PATH = "/home/donkey/donkeycar-models/trt/detector-A022.trt"

# Following values must be aligned with values in Hat !
# ROBOCARSHAT_PWM_OUT_THROTTLE_MIN    =   1000
# ROBOCARSHAT_PWM_OUT_THROTTLE_IDLE   =   1500
# ROBOCARSHAT_PWM_OUT_THROTTLE_MAX    =   2000
ROBOCARSHAT_PWM_OUT_STEERING_MIN    =   1180
ROBOCARSHAT_PWM_OUT_STEERING_IDLE   =   1520
ROBOCARSHAT_PWM_OUT_STEERING_MAX    =   1940
# ROBOCARSHAT_PWM_OUT_STEERING_INVERT    =   False

# Folowing values can be ajusted to normalized btzeen -1 and 1.
# If  ROBOCARSHAT_USE_AUTOCALIBRATION is used, IDLE values are automatically identified by the Hat
ROBOCARSHAT_PWM_IN_THROTTLE_MIN    =   1004
# ROBOCARSHAT_PWM_IN_THROTTLE_IDLE   =   1500
ROBOCARSHAT_PWM_IN_THROTTLE_MAX    =   1982
ROBOCARSHAT_PWM_IN_STEERING_MIN    =   995
# ROBOCARSHAT_PWM_IN_STEERING_IDLE   =   1500
ROBOCARSHAT_PWM_IN_STEERING_MAX    =   1985
# ROBOCARSHAT_PWM_IN_AUX_MIN    =   1000
# ROBOCARSHAT_PWM_IN_AUX_IDLE   =   1500
# ROBOCARSHAT_PWM_IN_AUX_MAX    =   2000

ROBOCARSHAT_CONTROL_LED = False
ROBOCARSHAT_CONTROL_LED_DEDICATED_TTY = '/dev/ttyACM0'

USE_ROBOCARSHAT_POWERTRAIN_CONTROLLER  = True

ROBOCARSHAT_THROTTLE_FLANGER = [-0.25, 0.4] # High speed flanger
# ROBOCARSHAT_THROTTLE_FLANGER = [-0.2, 0.25] # Low speed flanger

# PROFILES
SPRINT = {
    'OBSTACLE_DETECTOR_AVOIDANCE_ENABLED' : False,
    'OBSTACLE_DETECTOR_MANUAL_LANE' : True,
}

SLALOM = {
    'OBSTACLE_DETECTOR_AVOIDANCE_ENABLED' : True,
    'OBSTACLE_DETECTOR_MANUAL_LANE' : False,
}

COPILOT = {
    'ROBOCARSHAT_PILOT_MODE' : 'local_angle',
    'ROBOCARSHAT_LOCAL_ANGLE_FIX_THROTTLE' : None,
}

FIX_THROTTLE = {
    'ROBOCARSHAT_PILOT_MODE' : 'local_angle',
    'ROBOCARSHAT_LOCAL_ANGLE_FIX_THROTTLE' : 0.17
}

DUAL_THROTTLE = {
    'ROBOCARSHAT_PILOT_MODE' : 'local',
    'ROBOCARS_THROTTLE_DUAL_THROTTLE_MODEL' : 'True',
    'ROBOCARS_THROTTLE_LOW' : 0.19,
    'ROBOCARS_THROTTLE_HIGH' : 0.23,
}

ADAPTATIVE_STEERING = {
    'ROBOCARS_CTRL_ADAPTATIVE_STEERING_SCALER': 0.3,
}

# Race modes: SPRINT, SLALOM
# Throttles modes: FIX_THROTTLE, DUAL_THROTTLE, COPILOT
ROBOCARS_CONFIG_PROFILE = {**SPRINT, **COPILOT}

# python manage.py drive --type trt_behaviortrt --model ~/donkeycar-models/trt_4.6/model-067.trt
