OBSTACLE_DETECTOR_MODEL_PATH = "/home/donkey/donkeycar-models/trt/detector-A022.trt"

ROBOCARSHAT_SERIAL_PORT = '/dev/ttyTHS0'

# # Following values must be aligned with values in Hat !
# ROBOCARSHAT_PWM_OUT_THROTTLE_MIN    =   1000
# ROBOCARSHAT_PWM_OUT_THROTTLE_IDLE   =   1500
# ROBOCARSHAT_PWM_OUT_THROTTLE_MAX    =   2000
ROBOCARSHAT_PWM_OUT_STEERING_MIN    =   1055
ROBOCARSHAT_PWM_OUT_STEERING_IDLE   =   1465
ROBOCARSHAT_PWM_OUT_STEERING_MAX    =   1840
# ROBOCARSHAT_PWM_OUT_STEERING_INVERT    =   False

# Folowing values can be ajusted to normalized btzeen -1 and 1.
# If  ROBOCARSHAT_USE_AUTOCALIBRATION is used, IDLE values are automatically identified by the Hat
ROBOCARSHAT_PWM_IN_THROTTLE_MIN    =   981
# ROBOCARSHAT_PWM_IN_THROTTLE_IDLE   =   1412
ROBOCARSHAT_PWM_IN_THROTTLE_MAX    =   1867
ROBOCARSHAT_PWM_IN_STEERING_MIN    =   994
# ROBOCARSHAT_PWM_IN_STEERING_IDLE   =   1495
ROBOCARSHAT_PWM_IN_STEERING_MAX    =   1975
# ROBOCARSHAT_PWM_IN_AUX_MIN    =   1000
# ROBOCARSHAT_PWM_IN_AUX_IDLE   =   1500
# ROBOCARSHAT_PWM_IN_AUX_MAX    =   2000

ROBOCARSHAT_CONTROL_LED = True
ROBOCARSHAT_CONTROL_LED_DEDICATED_TTY = '/dev/ttyACM0'
ROBOCARSHAT_LED_MODEL = 'Feedback' #Alpine, Duo,

USE_ROBOCARSHAT_POWERTRAIN_CONTROLLER  = True

ROBOCARSHAT_THROTTLE_FLANGER = [-0.6, 0.45] # High speed flanger
# ROBOCARSHAT_THROTTLE_FLANGER = [-0.6, 0.30] # Low speed flanger

# PROFILES
SPRINT = {
    'OBSTACLE_DETECTOR_AVOIDANCE_ENABLED' : False,
    'OBSTACLE_DETECTOR_MANUAL_LANE' : True,
}

SLALOM = {
    'OBSTACLE_DETECTOR_AVOIDANCE_ENABLED' : True,
    'OBSTACLE_DETECTOR_MANUAL_LANE' : False,
}

COPILOT = {
    'ROBOCARSHAT_PILOT_MODE' : 'local_angle',
    'ROBOCARSHAT_LOCAL_ANGLE_FIX_THROTTLE' : None,
}

FIX_THROTTLE = {
    'ROBOCARSHAT_PILOT_MODE' : 'local_angle',
    'ROBOCARSHAT_LOCAL_ANGLE_FIX_THROTTLE' : 0.18
}

DUAL_THROTTLE = {
    'ROBOCARSHAT_PILOT_MODE' : 'local',
    'ROBOCARS_THROTTLE_DUAL_THROTTLE_MODEL' : 'True',
    'ROBOCARS_THROTTLE_LOW' : 0.15,
    'ROBOCARS_THROTTLE_HIGH' : 0.22,
}

ADAPTATIVE_STEERING = {
    'ROBOCARS_CTRL_ADAPTATIVE_STEERING_SCALER': 0.3,
}

# Race modes: SPRINT, SLALOM
# Throttles modes: FIX_THROTTLE, DUAL_THROTTLE, COPILOT
ROBOCARS_CONFIG_PROFILE = {**SPRINT, **COPILOT}
